### ISSUE TITLE
No tienes las Github Pages de acuerdo al estándar

### ISSUE THREAD

**Issue by rmortes** [ixtrunai/Worlds-radio#2]
Lo más normal es tener una rama `gh-pages`, que se autoconfigura como la rama de GP por defecto.

Also, si en la rama gh-pages pones el contenido de `/worlds/` en `/` puedes acceder directamente por https://ixtrunai.github.io/Worlds-radio/

Si haces la rama puedo hacerte una Pull Request desde la mía (actualmente alojada en https://rmortes.github.io/Worlds-radio/, aunque el chat no está funcional porque le tengo puesto tu origen)

**Comment by ixtrunai** [comment]
@rmortes Listo, dale a ese pull request cuándo gustes

**Comment by rmortes** [comment]
Se me hizo un poco tarde, y ya tienes la rama perfecta, así que cierro issue 👌
